version: '3.8'

services:
  api_service:
    build: ./api_server
    container_name: api_server
    env_file:
      - ./api_server/.env
    ports:
      - "8080:8080"
    volumes:
      - ./api_server:/usr/src/app
    restart: unless-stopped

  media_streaming_service:
    build: ./media_streaming_server
    container_name: media_streaming_server
    env_file:
      - ./media_streaming_server/.env
    ports:
      - "1935:1935"    # RTMP ingest
      - "8000:8000"    # HTTP (HLS)
    volumes:
      - ./media_streaming_server/hls:/usr/src/app/hls
      - ./media_streaming_server/recordings:/usr/src/app/recordings
    depends_on:
      - api_service
    restart: unless-stopped

  web_service:
    build: ./web_server
    container_name: web_server
    env_file:
      - ./web_server/.env
    ports:
      - "3000:3000"      # serve web frontend on port 8080
    volumes:
      - ./web_server:/usr/src/app
    depends_on:
      - api_service
      - media_streaming_service
    restart: unless-stopped
